# Generated by Django 4.2.27 on 2026-02-06 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_full_name', models.CharField(blank=True, max_length=60)),
                ('default_email', models.CharField(blank=True, max_length=60)),
                ('default_phone_number', models.CharField(blank=True, max_length=60)),
                ('default_country', models.CharField(blank=True, max_length=60)),
                ('default_postcode', models.CharField(blank=True, max_length=60)),
                ('default_city', models.CharField(blank=True, max_length=60)),
                ('default_town', models.CharField(blank=True, max_length=60)),
                ('default_street_address1', models.CharField(blank=True, max_length=60)),
                ('default_street_address2', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
