# Generated by Django 4.2.27 on 2026-02-06 15:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=60),
        ),
    ]
