# Generated by Django 4.2.27 on 2026-01-29 21:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=80)),
                ('town', models.CharField(max_length=80)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80)),
                ('delivery_method', models.CharField(choices=[('standard', 'Standard Delivery'), ('premium', 'Premium Delivery')])),
            ],
        ),
    ]
