# Generated by Django 4.2.27 on 2026-02-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick_and_mix', '0001_initial'),
        ('checkout', '0004_alter_order_delivery_cost_alter_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='pick_and_mix_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pick_and_mix.pickandmixbag'),
        ),
    ]
