# Generated by Django 4.2.27 on 2026-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_pick_and_mix_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
