# Generated by Django 4.2.27 on 2026-02-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_orderlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='pick_and_mix_item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
