# Generated by Django 4.2.27 on 2026-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_orderlineitem_pick_and_mix_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
