# Generated by Django 4.2.27 on 2026-02-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_dietarytag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickAndMixBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('max_weight_in_grams', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sweets', models.ManyToManyField(blank=True, related_name='pick_and_mix_bag', to='products.product')),
            ],
        ),
    ]
