# Generated by Django 4.2.27 on 2026-02-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pick_and_mix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickandmixbag',
            options={'ordering': ['name']},
        ),
    ]
