# Generated by Django 4.2.27 on 2026-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
