# Generated by Django 4.2.27 on 2026-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sweetcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarytag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
