# Generated by Django 4.2.27 on 2026-02-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_dietarytag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweetcategory',
            name='weight_in_grams',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
