# Generated by Django 4.2.27 on 2026-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sweetcategory_weight_in_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
