# Generated by Django 4.2.27 on 2026-03-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_stock_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweetcategory',
            options={'verbose_name': 'Sweet Category', 'verbose_name_plural': 'Sweet Categories'},
        ),
    ]
